POST https://graph-ql-nextjs.vercel.app/graphql HTTP/1.1
Host: graph-ql-nextjs-n61kivh1k-davi-alexandre.vercel.app
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
content-type: application/json
Content-Length: 1828
Origin: https://studio.apollographql.com
DNT: 1
Connection: keep-alive
Referer: https://studio.apollographql.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site

{"operationName":"Query","variables":{},"query":"query Query {\n  hello\n}"}